services:
  jenkins:
    ports:
      - "${JENKINS_HTTP_PORT:-49000}:8080"
      - "${JENKINS_AGENT_PORT:-50000}:50000"

  nginx:
    ports:
      - "${NGINX_HTTP_PORT:-9000}:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
